# This is a basic workflow to help you get started with Actions.

name: Deploy to preview channel

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and Build 
        run: npm install && npm run build
        env:
          CI: false
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "{{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 7d
          projectId: thinkific-badge
        env: 
          FIREBASE_CLI_PREVIEWS: hostingchannels
